// react/Pokemon.jsx
import { useState, useEffect } from "react";
import "./Pokemon.css";

function Pokemon() {
  const [error, setError] = useState(null);
  const [isLoaded, setIsLoaded] = useState(true);
  const [offset, setOffset] = useState(0);
  const [items, setItems] = useState([]);

  useEffect(() => {
    setIsLoaded(false);
    fetch(`https://pokeapi.co/api/v2/pokemon/?limit=10&offset=${offset}`)
      .then(res => res.json())
      .then(
        result => {
          setIsLoaded(true);
          setItems(result.results);
        },
        error => {
          setIsLoaded(true);
          setError(error);
        }
      );
  }, [offset]);

  function previous() {
    if (!isLoaded) return;
    setOffset(offset - 10);
  }

  function next() {
    if (!isLoaded) return;
    setOffset(offset + 10);
  }

  if (error) return "An error occurred";
  return (
    <div className="Pokemon">
      <h1>List of Pokémon</h1>
      <ul>
        {items.map(item => (
          <li key={item.url}>{item.name}</li>
        ))}
      </ul>
      <button disabled={offset === 0} onClick={previous}>
        Previous
      </button>
      <button disabled={offset >= 30} onClick={next}>
        Next
      </button>
    </div>
  );
}

export default Pokemon;

// solid/Pokemon.jsx
import styles from "./Pokemon.module.css";
import { createResource, createSignal } from "solid-js";

async function fetchNames(offset) {
  const response = await fetch(`https://pokeapi.co/api/v2/pokemon/?limit=10&offset=${offset}`);
  const obj = await response.json();
  return obj.results.map(a => a.name);
}

export default function Pokemon() {
  const [offset, setOffset] = createSignal(0);
  const [names] = createResource(offset, fetchNames);

  return (
    <div class={styles.pokemon}>
      <h1>List of Pokémon</h1>
      <ul>
        <For each={names()}>{item => <li>{item}</li>}</For>
      </ul>
      <button disabled={offset() === 0} onclick={e => setOffset(offset() - 10)}>
        Previous
      </button>
      <button disabled={offset() === 50} onclick={e => setOffset(offset() + 10)}>
        Next
      </button>
    </div>
  );
}
