// svelte/Pokemon.svelte
<script>
  import { onMount } from "svelte";

  let offset = 0;
  let names = [];

  async function fetchNames() {
    const response = await fetch(`https://pokeapi.co/api/v2/pokemon/?limit=10&offset=${offset}`);
    const data = await response.json();
    names = data.results.map(a => a.name);
  }

  onMount(fetchNames);

  function next() {
    offset += 10;
    fetchNames();
  }

  function prev() {
    offset -= 10;
    fetchNames();
  }
</script>

<div class="pokemon">
  <h1>List of Pokémon</h1>
  <ul>
    {#each names as name}
      <li>{name}</li>
    {/each}
  </ul>
  <button on:click={prev} disabled={offset === 0}>Previous</button>
  <button on:click={next} disabled={offset === 50}>Next</button>
</div>

<style>
  .pokemon {
    font-family: sans-serif;
  }

  .pokemon ul {
    font-size: 1rem;
    line-height: 1.2rem;
    min-height: calc(1.2rem * 10);
  }
</style>

// vue/Pokemon.vue
<style>
.pokemon ul {
  min-height: calc(1rem * 10);
}
.pokemon li {
  height: 1rem;
}
</style>

<template>
  <div class="pokemon">
    <h1>List of Pokémon</h1>
    <ul v-if="names.length > 0">
      <li v-for="name in names">{{ name }}</li>
    </ul>
    <button @click="prev" v-bind:disabled="offset === 0">Previous</button>
    <button @click="next" v-bind:disabled="offset >= 50">Next</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      offset: 0,
      names: [, , , , , , , , , ,],
    };
  },
  methods: {
    prev() {
      this.offset -= 10;
      this.update();
    },

    next() {
      this.offset += 10;
      this.update();
    },

    async update() {
      try {
        const response = await fetch(`https://pokeapi.co/api/v2/pokemon/?limit=10&offset=${this.offset}`);
        if (!response.ok) return;
        const obj = await response.json();
        this.names = obj.results.map(a => a.name);
      } catch (error) {}
    },
  },
  created() {
    this.update();
  },
};
</script>
